FROM registry.astralinux.ru/library/astra/ubi18:1.8.1-mg13.3.0

RUN apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off; master_process on;"]